// Direct ModelArk text streaming for Aurora Video Agent surfaces.
// Uses the current OpenAI-compatible Chat Completions SSE contract with stream=true.
// `service_tier:auto` lets eligible guaranteed-TPM capacity be used automatically.
// Secrets are server-only; ARK_API_KEY/BYTEPLUS_API_KEY are never exposed to clients.
const DEFAULT_BASE="https://ark.ap-southeast.bytepluses.com/api/v3";
export type ModelArkStreamMessage={role:"system"|"user"|"assistant";content:unknown};
export function modelArkStreamConfig(){return{key:process.env.ARK_API_KEY||process.env.BYTEPLUS_API_KEY||"",base:(process.env.ARK_BASE_URL||process.env.BYTEPLUS_BASE_URL||DEFAULT_BASE).replace(/\/+$/, ""),model:process.env.MODELARK_TEXT_MODEL||process.env.BYTEPLUS_TEXT_MODEL||"doubao-seed-2-0-pro",serviceTier:process.env.MODELARK_SERVICE_TIER||"auto"};}
export function hasModelArkStreaming(){return Boolean(modelArkStreamConfig().key);}
export async function streamModelArkText(args:{messages:ModelArkStreamMessage[];model?:string;temperature?:number;maxTokens?:number;signal?:AbortSignal}):Promise<Response>{const cfg=modelArkStreamConfig();if(!cfg.key)throw new Error("ModelArk streaming is not configured: set ARK_API_KEY or BYTEPLUS_API_KEY");const upstream=await fetch(`${cfg.base}/chat/completions`,{method:"POST",headers:{Authorization:`Bearer ${cfg.key}`,"Content-Type":"application/json",Accept:"text/event-stream"},signal:args.signal,body:JSON.stringify({model:args.model||cfg.model,messages:args.messages,stream:true,stream_options:{include_usage:true},service_tier:cfg.serviceTier,temperature:args.temperature??0.7,max_tokens:args.maxTokens??4096})});if(!upstream.ok||!upstream.body){const body=await upstream.text().catch(()=>"");throw new Error(`ModelArk stream ${upstream.status}: ${body.slice(0,800)}`);}return upstream;}
export function wrapModelArkSSE(upstream:Response,signal?:AbortSignal):Response{const encoder=new TextEncoder(),decoder=new TextDecoder();const body=new ReadableStream<Uint8Array>({async start(controller){const reader=upstream.body!.getReader();let buffer="",finished=false;const send=(event:string,data:unknown)=>controller.enqueue(encoder.encode(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`));try{send("start",{provider:"modelark",model:modelArkStreamConfig().model,serviceTier:modelArkStreamConfig().serviceTier});while(!finished){if(signal?.aborted){await reader.cancel();return;}const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split(/\r?\n/);buffer=lines.pop()||"";for(const line of lines){const trimmed=line.trim();if(!trimmed.startsWith("data:"))continue;const data=trimmed.slice(5).trim();if(data==="[DONE]"){send("done",{reason:"provider_done"});finished=true;break;}try{const chunk=JSON.parse(data) as {choices?:Array<{delta?:{content?:unknown}}>;usage?:unknown};const delta=chunk.choices?.[0]?.delta?.content;if(typeof delta==="string"&&delta)send("delta",{text:delta});if(chunk.usage)send("usage",chunk.usage);}catch{/* split/unknown provider frame */}}}if(!finished)send("done",{reason:"eof"});}catch(error){send("error",{message:error instanceof Error?error.message:String(error)});}finally{reader.releaseLock();controller.close();}}});return new Response(body,{headers:{"Content-Type":"text/event-stream; charset=utf-8","Cache-Control":"no-cache, no-transform","Connection":"keep-alive","X-Accel-Buffering":"no","Access-Control-Allow-Origin":"*"}});}
