/** Shared Aurora Video Agent memory contract, adapted from the standalone agent family. */
export type MemoryStatus="DRAFT"|"PROPOSED"|"APPROVED"|"LOCKED"|"REJECTED"|"ARCHIVED";
export type ReferenceRole="AUTHORITATIVE"|"SUPPORTING"|"EXPLORATORY"|"REJECTED";
export type NotebookType="character"|"identity"|"face"|"body"|"hair"|"tattoo"|"jewelry"|"wardrobe"|"location"|"world"|"prop"|"style"|"camera"|"lighting"|"prompt_recipe"|"playbook"|"story"|"scene"|"shot"|"reference"|"continuity_rule"|"approved_generation"|"rejected_generation"|"lesson"|"general";
export type LockType="identity"|"face"|"body"|"hair"|"wardrobe"|"location"|"world"|"camera"|"style"|"composition"|"performance"|"audio"|"continuity"|"brand"|"custom";
export interface ReferenceAsset{id:string;title:string;uri:string;purpose:string;role:ReferenceRole;tags:string[];approvedAt?:string}
export interface ContextSection{id:string;key:string;title:string;content:string;status:MemoryStatus;locked:boolean;referenceIds:string[];tags:string[];updatedAt:string}
export interface NotebookEntry{id:string;type:NotebookType;title:string;content:string;status:MemoryStatus;tags:string[];referenceIds:string[];linkedIds:string[];confidence:number;source?:string;updatedAt:string}
export interface ProductionLock{id:string;type:LockType;title:string;rule:string;status:"APPROVED"|"LOCKED";scope:string[];referenceIds:string[]}
export interface AcceptanceCriterion{id:string;rule:string;required:boolean;scope:string[]}
export interface GenerationRecord{id:string;taskType:string;prompt:string;contextIds:string[];notebookIds:string[];referenceIds:string[];lockIds:string[];modelId?:string;assetIds:string[];status:"GENERATED"|"APPROVED"|"REJECTED";failureCodes:string[];createdAt:string}
export interface ProjectMemory{projectId:string;context:ContextSection[];notebook:NotebookEntry[];references:ReferenceAsset[];locks:ProductionLock[];acceptance:AcceptanceCriterion[];generations:GenerationRecord[]}
const normalize=(s:string)=>s.toLowerCase().trim();
export function retrieveProjectMemory(memory:ProjectMemory,taskType:string,query=""){const q=new Set((`${taskType} ${query}`).toLowerCase().split(/[^a-z0-9]+/).filter(Boolean));const hit=(s:string)=>s.toLowerCase().split(/[^a-z0-9]+/).some(x=>q.has(x));return{context:memory.context.filter(x=>x.locked||hit(`${x.key} ${x.title} ${x.content}`)),notebook:memory.notebook.filter(x=>x.status==="APPROVED"||x.status==="LOCKED"||hit(`${x.type} ${x.title} ${x.content}`)),references:memory.references.filter(x=>x.role!=="REJECTED"),locks:memory.locks.filter(x=>x.status==="LOCKED"||x.scope.length===0||x.scope.some(s=>q.has(normalize(s)))),acceptance:memory.acceptance.filter(x=>x.scope.length===0||x.scope.some(s=>q.has(normalize(s))))};}
export function buildGenerationContext(memory:ProjectMemory,taskType:string,userInstruction:string){return{projectId:memory.projectId,taskType,userInstruction,...retrieveProjectMemory(memory,taskType,userInstruction),priority:["HARD_LOCKS","AUTHORITATIVE_REFERENCES","ACCEPTANCE_CRITERIA","ACTIVE_CONTEXT","APPROVED_NOTEBOOK","APPROVED_GENERATIONS","USER_INSTRUCTION"]}}
export function toPromptContext(context:ReturnType<typeof buildGenerationContext>):string{return JSON.stringify({projectId:context.projectId,taskType:context.taskType,priority:context.priority,locks:context.locks,acceptance:context.acceptance,context:context.context,notebook:context.notebook,references:context.references},null,2)}
export function checkLockConflicts(instruction:string,locks:ProductionLock[]){const t=normalize(instruction);return locks.filter(l=>{const r=normalize(l.rule);return(r.includes("no sunglasses")&&t.includes("sunglasses"))||(r.includes("camera locked")&&/(camera|pan|zoom|dolly|handheld|tracking)/.test(t))})}
