import { Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import {
  Flame,
  Sparkles,
  TrendingUp,
  Zap,
  Video,
  Play,
  RotateCcw,
  ArrowRight,
  MessageCircle,
  Heart,
  Share2,
  Music,
  Users,
} from "lucide-react";
import { SPIN_COUNT } from "@/lib/spin-engine";
import auroraLogo from "@/assets/aurora-logo.png.asset.json";
// One creator, many posts — the whole grid is the SAME female avatar identity.
// Profile photo is the identity reference; the grid tiles are REAL Spin output
// (not the same photo re-cropped) — genuinely different outfits/scenes/poses,
// generated by Aurora from that one reference photo.
import joshPinkPortrait from "@/assets/josh/josh-pink-sideprofile.png.asset.json";
import joshMoodyMic from "@/assets/josh/josh-moody-mic.jpg.asset.json";
import joshColorsSession from "@/assets/josh/josh-colors-session.png.asset.json";
import joshNeonSeated from "@/assets/josh/josh-neon-seated.png.asset.json";

const GRID_PHOTOS = [
  joshPinkPortrait.url,
  joshMoodyMic.url,
  joshColorsSession.url,
  joshNeonSeated.url,
] as const;

// Accurate full-color TikTok logo (official glyph, layered cyan/red/white).
function TikTokLogo({ className }: { className?: string }) {
  const d =
    "M12.525.02c1.31-.02 2.61-.01 3.91-.02.08 1.53.63 3.09 1.75 4.17 1.12 1.11 2.7 1.62 4.24 1.79v4.03c-1.44-.05-2.89-.35-4.2-.97-.57-.26-1.1-.59-1.62-.93-.01 2.92.01 5.84-.02 8.75-.08 1.4-.54 2.79-1.35 3.94-1.31 1.92-3.58 3.17-5.91 3.21-1.43.08-2.86-.31-4.08-1.03-2.02-1.19-3.44-3.37-3.65-5.71-.02-.5-.03-1-.01-1.49.18-1.9 1.12-3.72 2.58-4.96 1.66-1.44 3.98-2.13 6.15-1.72.02 1.48-.04 2.96-.04 4.44-.99-.32-2.15-.23-3.02.37-.63.41-1.11 1.04-1.36 1.75-.21.51-.15 1.07-.14 1.61.24 1.64 1.82 3.02 3.5 2.87 1.12-.01 2.19-.66 2.77-1.61.19-.33.4-.67.41-1.06.1-1.79.06-3.57.07-5.36.01-4.03-.01-8.05.02-12.07z";
  return (
    <svg viewBox="0 0 24 24" className={className} role="img" aria-label="TikTok">
      <path d={d} transform="translate(-0.7,-0.7)" fill="#25F4EE" />
      <path d={d} transform="translate(0.7,0.7)" fill="#FE2C55" />
      <path d={d} fill="#FFFFFF" />
    </svg>
  );
}

const PIECES = [
  { label: "Lyric video hook", kind: "video", color: "from-pink-500 to-rose-500" },
  { label: "Beat-sync visual", kind: "video", color: "from-fuchsia-500 to-pink-500" },
  { label: "Cover art reveal", kind: "image", color: "from-violet-500 to-fuchsia-500" },
  { label: "Story teaser", kind: "image", color: "from-emerald-500 to-teal-500" },
  { label: "Color-grade variant", kind: "image", color: "from-cyan-400 to-sky-500" },
  { label: "YouTube Short", kind: "video", color: "from-red-500 to-orange-500" },
  { label: "Lip-sync clip", kind: "video", color: "from-pink-500 to-violet-500" },
  { label: "Album teaser", kind: "image", color: "from-yellow-400 to-amber-500" },
  { label: "Vertical poster", kind: "image", color: "from-purple-500 to-violet-600" },
  { label: "Performance clip", kind: "video", color: "from-rose-500 to-pink-500" },
  { label: "Captioned hook", kind: "image", color: "from-fuchsia-400 to-purple-500" },
  { label: "Single cover", kind: "image", color: "from-blue-500 to-indigo-500" },
] as const;

// Single source of truth for the post count — matches the real Spin backend
// (SPIN_COUNT) so the landing page never advertises a number the product
// doesn't deliver. PIECES/VIEWS/CAPTIONS below only need enough entries to
// fill the 6-tile grid preview; the reveal counter runs to COUNT.
const COUNT: number = SPIN_COUNT;

// Per-tile view counts, captions, and framing so one face reads as a full feed.
const VIEWS = [
  "1.2M",
  "845K",
  "2.1M",
  "96K",
  "540K",
  "1.9M",
  "430K",
  "72K",
  "688K",
  "910K",
  "28.4K",
  "1.1M",
] as const;

const CAPTIONS = [
  "POV: my single dropped 🎤",
  "cover art reveal 🎨",
  "made this in 30s 🤯",
  "beat drop at 0:08 🔊",
  "neon color grade ✨",
  "lyric video hook 🎬",
  "lip-sync to my track 🎵",
  "when the beat drops 😳",
  "album teaser 🔥",
  "performance clip, zero setup",
  "auto-captioned lyrics 💬",
  "single cover 🖼️",
] as const;

const SAMPLE_HOOKS = [
  "POV: my single just charted",
  "beat drop at 0:08 hits different",
  "Afrobeats summer anthem 2025",
  "how I made my music video in 30s",
];

// Seedance 2.0 × Claude fan-out: one source photo → 5 distinct TikTok posts
const FANOUT_POSTS = [
  {
    photo: joshPinkPortrait.url,
    hook: "THIS TRACK HITS DIFFERENT 🔥",
    views: "1.2M",
    likes: "84K",
    comments: "2.1K",
    sound: "Aurora Spin Beat",
  },
  {
    photo: (joshMoodyMic as { url: string }).url,
    hook: "STUDIO SESSION DROPPED 📸",
    views: "845K",
    likes: "61K",
    comments: "1.4K",
    sound: "Original sound",
  },
  {
    photo: (joshColorsSession as { url: string }).url,
    hook: "AURORA MADE THIS IN 30S ✨",
    views: "2.1M",
    likes: "143K",
    comments: "4.2K",
    sound: "Aurora Spin Beat",
  },
  {
    photo: (joshNeonSeated as { url: string }).url,
    hook: "SAME FACE. 30 POSTS. 🎯",
    views: "540K",
    likes: "38K",
    comments: "892",
    sound: "Original sound",
  },
  {
    photo: "/josh/josh-pink-mic-portrait.jpg",
    hook: "AFROBEATS ANTHEM 2025 🎵",
    views: "1.9M",
    likes: "112K",
    comments: "3.7K",
    sound: "Aurora Spin Beat",
  },
] as const;

export function ViralEngine() {
  const navigate = useNavigate();
  const [hook, setHook] = useState("");
  const [phase, setPhase] = useState<"idle" | "spinning" | "done">("idle");
  const [revealed, setRevealed] = useState(0);
  const timerRef = useRef<number | null>(null);

  const startSpin = (text?: string) => {
    const value =
      (text ?? hook).trim() || SAMPLE_HOOKS[Math.floor(Math.random() * SAMPLE_HOOKS.length)];
    setHook(value);
    setRevealed(0);
    setPhase("spinning");
  };

  const reset = () => {
    setPhase("idle");
    setRevealed(0);
  };

  useEffect(() => {
    if (phase !== "spinning") return;
    let i = 0;
    timerRef.current = window.setInterval(() => {
      i += 1;
      setRevealed(i);
      if (i >= COUNT) {
        if (timerRef.current) window.clearInterval(timerRef.current);
        setPhase("done");
      }
    }, 70);
    return () => {
      if (timerRef.current) window.clearInterval(timerRef.current);
    };
  }, [phase]);

  const goToSpin = () => {
    navigate({ to: "/spin", search: { prompt: hook || undefined, jobId: undefined } });
  };

  return (
    <section className="relative z-10 mx-4 md:mx-12 my-12 overflow-hidden rounded-[32px] border border-white/10 bg-gradient-to-br from-[#1a0822] via-[#0f0820] to-[#06070d] animate-fade-in">
      <div
        className="absolute inset-0 pointer-events-none opacity-50"
        style={{
          background:
            "radial-gradient(circle at 90% 0%, rgba(236,72,153,.28), transparent 40%), radial-gradient(circle at 0% 100%, rgba(168,85,247,.28), transparent 40%)",
        }}
      />
      <div className="relative px-6 py-10 md:px-12 md:py-14">
        {/* TikTok × Aurora pulsing lockup — real logos */}
        <div className="mb-6 flex items-center justify-center gap-5">
          {/* Actual TikTok logo */}
          <div className="relative grid place-items-center">
            <span className="absolute inset-0 rounded-2xl bg-pink-500/40 blur-2xl animate-pulse" />
            <div className="relative grid size-12 md:size-14 place-items-center rounded-2xl bg-black shadow-lg shadow-pink-500/30">
              <TikTokLogo className="size-7 md:size-8" />
            </div>
          </div>
          <span className="text-2xl md:text-3xl font-black text-white/60">×</span>
          {/* Actual Aurora logo */}
          <div className="relative grid place-items-center">
            <span className="absolute inset-0 rounded-2xl bg-fuchsia-500/40 blur-2xl animate-pulse [animation-delay:300ms]" />
            <div className="relative grid size-12 md:size-14 place-items-center overflow-hidden rounded-2xl bg-white/5 ring-1 ring-white/10 shadow-lg shadow-fuchsia-500/40">
              <img
                src={auroraLogo.url}
                alt="Aurora"
                loading="lazy"
                decoding="async"
                className="size-full object-contain p-1.5"
              />
            </div>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <span className="inline-flex items-center gap-2 rounded-full border border-pink-300/20 bg-pink-300/10 px-3 py-1 text-[11px] font-semibold uppercase tracking-widest text-pink-200">
            <Flame className="size-3.5" /> Spin 30
          </span>
          <span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[11px] font-semibold uppercase tracking-widest text-white/70">
            <TrendingUp className="size-3.5" /> TikTok · Reels · Shorts · X
          </span>
          <span className="inline-flex items-center gap-2 rounded-full border border-violet-400/20 bg-violet-400/10 px-3 py-1 text-[11px] font-semibold uppercase tracking-widest text-violet-300">
            <Sparkles className="size-3.5" /> Claude + Seedance 2.0
          </span>
        </div>

        <h2 className="mt-4 max-w-3xl text-3xl font-extrabold tracking-tight text-white md:text-5xl">
          One prompt.{" "}
          <span className="bg-gradient-to-r from-pink-300 via-fuchsia-300 to-violet-300 bg-clip-text text-transparent">
            {COUNT} posts. Posted.
          </span>
        </h2>
        <p className="mt-3 max-w-2xl text-base leading-7 text-white/72 md:text-lg">
          Type your hook. Aurora uses <strong className="text-white">Claude + Seedance 2.0</strong> to generate{" "}
          <strong className="text-white">{COUNT} scroll-stopping posts</strong> — lyric hooks, cover reveals,
          performance clips, styled portraits — a full month of content from one idea.
        </p>

        {/* Inline interactive 1 → N demo */}
        <div className="mt-6 rounded-3xl border border-white/10 bg-black/50 backdrop-blur p-4 md:p-5">
          <div className="flex flex-col gap-3">
            <label className="text-[11px] uppercase tracking-[0.2em] text-pink-200/80">
              Try it · type a hook idea
            </label>
            <div className="flex flex-col sm:flex-row gap-2">
              <input
                value={hook}
                onChange={(e) => setHook(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    e.preventDefault();
                    startSpin();
                  }
                }}
                placeholder="POV: my single just charted"
                className="flex-1 rounded-full bg-white/[0.06] border border-white/10 px-4 py-3 text-sm text-white placeholder:text-white/35 outline-none focus:border-pink-300/60 focus:bg-white/[0.08]"
              />
              {phase === "spinning" ? (
                <button
                  disabled
                  className="inline-flex items-center justify-center gap-2 rounded-full bg-white/10 px-5 py-3 text-sm font-bold text-white/70"
                >
                  <Sparkles className="size-4 animate-spin" />
                  Generating {revealed}/{COUNT}
                </button>
              ) : phase === "done" ? (
                <button
                  onClick={reset}
                  className="inline-flex items-center justify-center gap-2 rounded-full border border-white/15 bg-white/5 px-5 py-3 text-sm font-bold text-white hover:bg-white/10"
                >
                  <RotateCcw className="size-4" />
                  Reset
                </button>
              ) : (
                <button
                  onClick={() => startSpin()}
                  className="inline-flex items-center justify-center gap-2 rounded-full bg-gradient-to-r from-pink-400 to-fuchsia-500 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-fuchsia-500/30 hover:opacity-95"
                >
                  <Play className="size-4 fill-white" />
                  Generate 1 → {COUNT}
                </button>
              )}
            </div>
            <div className="flex flex-wrap gap-1.5">
              {SAMPLE_HOOKS.map((h) => (
                <button
                  key={h}
                  type="button"
                  onClick={() => startSpin(h)}
                  className="text-[11px] rounded-full border border-white/10 bg-white/[0.04] px-2.5 py-1 text-white/65 hover:text-white hover:border-pink-300/40 hover:bg-pink-300/10"
                >
                  {h}
                </button>
              ))}
            </div>
          </div>

          {/* Seedance 2.0 × Claude fan-out: 1 source → 5 distinct TikTok posts */}
          <div className="mt-6">
            {/* Source image — centered at top */}
            <div className="flex flex-col items-center mb-3">
              <div
                className="relative w-[58px] overflow-hidden rounded-2xl ring-2 ring-fuchsia-400/70 shadow-[0_0_28px_-4px_rgba(217,70,239,0.6)]"
                style={{ aspectRatio: "9/16" }}
              >
                <img
                  src={(joshColorsSession as { url: string }).url}
                  alt="Source"
                  loading="lazy"
                  className="w-full h-full object-cover"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent" />
              </div>
              <div className="mt-2 flex items-center gap-1.5 rounded-full border border-fuchsia-400/30 bg-fuchsia-500/15 px-2.5 py-0.5">
                <span className="text-[9px] font-bold uppercase tracking-widest text-fuchsia-200">
                  1 INPUT · YOUR HOOK
                </span>
              </div>
            </div>

            {/* Fan-out connector — stem → horizontal branch → 5 drops */}
            <div className="relative mx-auto mb-0 h-6 max-w-[540px]">
              <div className="absolute left-1/2 top-0 h-2.5 w-px -translate-x-1/2 bg-fuchsia-400/40" />
              <div className="absolute left-[9%] right-[9%] top-[10px] h-px bg-fuchsia-400/30" />
              {([9, 27, 50, 73, 91] as const).map((pct) => (
                <div
                  key={pct}
                  className="absolute top-[10px] h-3 w-px bg-fuchsia-400/30"
                  style={{ left: `${pct}%` }}
                />
              ))}
            </div>

            {/* 5 TikTok post frames */}
            <div className="flex justify-center gap-1.5 md:gap-2 overflow-x-auto pb-2 -mx-1 px-1">
              {FANOUT_POSTS.map((post, i) => {
                const lit = i < revealed || phase === "done";
                const active = phase === "spinning" && i === revealed;
                return (
                  <div
                    key={post.hook}
                    className={`relative shrink-0 w-[88px] md:w-[100px] overflow-hidden rounded-[14px] border transition-all duration-500 ${
                      lit
                        ? "border-white/30 opacity-100 scale-[1.02]"
                        : "border-white/10 opacity-50 saturate-[0.3]"
                    }`}
                    style={{ aspectRatio: "9/16" }}
                  >
                    <img
                      src={post.photo}
                      alt={post.hook}
                      loading="lazy"
                      className="w-full h-full object-cover"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/10 to-black/25 pointer-events-none" />

                    {/* View count — top left */}
                    <div className="absolute top-1.5 left-1.5 flex items-center gap-0.5">
                      <Play className="size-2 fill-white text-white" />
                      <span className="text-[8px] font-bold text-white drop-shadow-sm">
                        {post.views}
                      </span>
                    </div>

                    {/* Right sidebar — engagement icons */}
                    <div className="absolute right-1.5 bottom-14 flex flex-col items-center gap-2">
                      <div className="flex flex-col items-center gap-0.5">
                        <Heart className="size-[14px] text-white/85" />
                        <span className="text-[7px] text-white/55">{post.likes}</span>
                      </div>
                      <div className="flex flex-col items-center gap-0.5">
                        <MessageCircle className="size-[14px] text-white/85" />
                        <span className="text-[7px] text-white/55">{post.comments}</span>
                      </div>
                      <Share2 className="size-[14px] text-white/85" />
                    </div>

                    {/* Bottom caption */}
                    <div className="absolute inset-x-0 bottom-0 p-1.5">
                      <p className="text-[7px] text-white/45 mb-0.5">@aurora.creator</p>
                      <p className="text-[9px] md:text-[10px] font-black text-white leading-tight line-clamp-2">
                        {post.hook}
                      </p>
                      <div className="mt-0.5 flex items-center gap-0.5">
                        <Music className="size-2 text-white/35" />
                        <p className="text-[7px] text-white/35 truncate">{post.sound}</p>
                      </div>
                    </div>

                    {/* TikTok logo — bottom right */}
                    <div className="absolute bottom-1.5 right-1.5">
                      <TikTokLogo className="size-3.5 opacity-50" />
                    </div>

                    {active && (
                      <div className="absolute inset-0 grid place-items-center bg-white/5 backdrop-blur-[2px]">
                        <Sparkles className="size-5 animate-spin text-fuchsia-300" />
                      </div>
                    )}
                  </div>
                );
              })}
            </div>

            {/* Results analytics bar */}
            <div className="mt-4 grid grid-cols-3 overflow-hidden rounded-xl border border-white/10 bg-white/[0.04]">
              {[
                { icon: <Play className="size-3.5" />, n: "6.1M", l: "Views" },
                { icon: <Users className="size-3.5" />, n: "21K", l: "New followers" },
                { icon: <Sparkles className="size-3.5" />, n: `${COUNT}`, l: "Posts shipped" },
              ].map((s, i) => (
                <div
                  key={s.l}
                  className={`flex flex-col items-center py-3 gap-0.5 ${i > 0 ? "border-l border-white/10" : ""}`}
                >
                  <div className="flex items-center gap-1.5">
                    <span className="text-fuchsia-300/70">{s.icon}</span>
                    <span className="text-base md:text-lg font-bold text-white">{s.n}</span>
                  </div>
                  <span className="text-[9px] uppercase tracking-wider text-white/40">{s.l}</span>
                </div>
              ))}
            </div>
          </div>

          {phase === "done" && (
            <div className="mt-5 rounded-2xl border border-pink-300/30 bg-pink-300/10 px-4 py-3 flex flex-col sm:flex-row sm:items-center justify-between gap-3 animate-fade-in">
              <p className="text-sm text-white">
                <strong className="text-pink-200">{COUNT} pieces ready</strong> from "{hook}". Open Spin Studio to generate them for real — takes under 60 seconds.
              </p>
              <button
                onClick={goToSpin}
                className="inline-flex items-center justify-center gap-2 rounded-full bg-gradient-to-r from-pink-400 to-fuchsia-500 px-4 py-2 text-sm font-bold text-white shadow-lg shadow-fuchsia-500/30 hover:opacity-95"
              >
                Open Spin Studio <ArrowRight className="size-4" />
              </button>
            </div>
          )}
        </div>

        {/* Feature stack */}
        <div className="mt-6 grid gap-3 md:grid-cols-3">
          <Feature
            icon={<Video className="size-4" />}
            title="Beat-synced cuts"
            body="Openers that hit on the downbeat — 0–3s hooks proven to stop the scroll on TikTok & Reels."
          />
          <Feature
            icon={<Sparkles className="size-4" />}
            title="Genre-ready aesthetics"
            body="Afrobeats, Trap, Drill, neon and Y2K looks — color-grade swaps in one tap."
          />
          <Feature
            icon={<Zap className="size-4" />}
            title="Lip-sync to your track"
            body="Drop your song — Aurora aligns mouth shapes frame-perfect to your vocals."
          />
        </div>

        {/* One primary CTA */}
        <div className="mt-6 flex flex-wrap items-center gap-3">
          <Link
            to="/spin"
            search={{ prompt: undefined, jobId: undefined }}
            className="inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-pink-400 to-fuchsia-500 px-6 py-3 text-sm font-bold text-white no-underline shadow-lg shadow-fuchsia-500/30 hover:opacity-95"
          >
            Open Spin Studio · 1 → {COUNT} <ArrowRight className="size-4" />
          </Link>
        </div>
      </div>
    </section>
  );
}

function Stat({ n, l }: { n: string; l: string }) {
  return (
    <div className="flex flex-col items-center">
      <span className="text-[16px] font-bold leading-none text-white">{n}</span>
      <span className="mt-1 text-[12px] text-white/55">{l}</span>
    </div>
  );
}

function Feature({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) {
  return (
    <div className="rounded-xl border border-white/10 bg-white/[0.04] p-4">
      <div className="flex items-center gap-2 text-pink-200">
        {icon}
        <span className="text-sm font-semibold text-white">{title}</span>
      </div>
      <p className="mt-1 text-sm text-white/65">{body}</p>
    </div>
  );
}
