// Aurora AI Intelligence Router — Extended Provider Registry
// ModelArk is first-class for creative video/image/script reasoning when ARK_API_KEY is configured.
import { createOpenAICompatible } from "@ai-sdk/openai-compatible";
export type RouterProvider={name:string;displayName:string;enabled:boolean;model:string;make:()=>ReturnType<typeof createOpenAICompatible>};
export function buildProviderRegistry():Map<string,RouterProvider>{
 const registry=new Map<string,RouterProvider>(); const add=(p:RouterProvider)=>registry.set(p.name,p);
 add({name:"modelark",displayName:"ModelArk / BytePlus",enabled:!!(process.env.ARK_API_KEY||process.env.BYTEPLUS_API_KEY),model:process.env.MODELARK_TEXT_MODEL||"doubao-seed-2-0-pro",make:()=>createOpenAICompatible({name:"modelark",baseURL:(process.env.ARK_BASE_URL||process.env.BYTEPLUS_BASE_URL||"https://ark.ap-southeast.bytepluses.com/api/v3").replace(/\/+$/, ""),headers:{Authorization:`Bearer ${process.env.ARK_API_KEY||process.env.BYTEPLUS_API_KEY}`}})});
 add({name:"claude",displayName:"Claude (Anthropic)",enabled:!!process.env.ANTHROPIC_API_KEY,model:"claude-sonnet-4-5",make:()=>createOpenAICompatible({name:"anthropic",baseURL:"https://api.anthropic.com/v1",headers:{Authorization:`Bearer ${process.env.ANTHROPIC_API_KEY}`}})});
 add({name:"gemini",displayName:"Gemini (Google)",enabled:!!process.env.GEMINI_API_KEY||!!process.env.AI_INTEGRATIONS_GEMINI_API_KEY,model:"gemini-2.5-flash",make:()=>{const key=process.env.AI_INTEGRATIONS_GEMINI_API_KEY||process.env.GEMINI_API_KEY!;const base=process.env.AI_INTEGRATIONS_GEMINI_BASE_URL||"https://generativelanguage.googleapis.com/v1beta/openai";return createOpenAICompatible({name:"gemini",baseURL:base,headers:{Authorization:`Bearer ${key}`}})}});
 add({name:"grok",displayName:"Grok (xAI)",enabled:!!process.env.XAI_API_KEY,model:"grok-3-mini",make:()=>createOpenAICompatible({name:"xai",baseURL:"https://api.x.ai/v1",headers:{Authorization:`Bearer ${process.env.XAI_API_KEY}`}})});
 add({name:"qwen",displayName:"Qwen (OpenRouter)",enabled:!!process.env.OPENROUTER_API_KEY,model:"qwen/qwen3-235b-a22b:free",make:()=>createOpenAICompatible({name:"openrouter-qwen",baseURL:"https://openrouter.ai/api/v1",headers:{Authorization:`Bearer ${process.env.OPENROUTER_API_KEY}`,"HTTP-Referer":"https://aurora.app","X-Title":"Aurora AI"}})});
 add({name:"qwen-coder",displayName:"Qwen Coder (OpenRouter)",enabled:!!process.env.OPENROUTER_API_KEY,model:"qwen/qwen2.5-coder-32b-instruct",make:()=>createOpenAICompatible({name:"openrouter-qwen-coder",baseURL:"https://openrouter.ai/api/v1",headers:{Authorization:`Bearer ${process.env.OPENROUTER_API_KEY}`,"HTTP-Referer":"https://aurora.app","X-Title":"Aurora AI"}})});
 add({name:"deepseek",displayName:"DeepSeek (OpenRouter)",enabled:!!process.env.OPENROUTER_API_KEY,model:"deepseek/deepseek-chat-v3-0324:free",make:()=>createOpenAICompatible({name:"openrouter-deepseek",baseURL:"https://openrouter.ai/api/v1",headers:{Authorization:`Bearer ${process.env.OPENROUTER_API_KEY}`,"HTTP-Referer":"https://aurora.app","X-Title":"Aurora AI"}})});
 add({name:"deepseek-coder",displayName:"DeepSeek Coder (OpenRouter)",enabled:!!process.env.OPENROUTER_API_KEY,model:"deepseek/deepseek-r1-distill-qwen-32b",make:()=>createOpenAICompatible({name:"openrouter-deepseek-coder",baseURL:"https://openrouter.ai/api/v1",headers:{Authorization:`Bearer ${process.env.OPENROUTER_API_KEY}`,"HTTP-Referer":"https://aurora.app","X-Title":"Aurora AI"}})});
 if(process.env.GROQ_API_KEY)add({name:"llama",displayName:"Llama (Groq)",enabled:true,model:"llama-3.3-70b-versatile",make:()=>createOpenAICompatible({name:"groq",baseURL:"https://api.groq.com/openai/v1",headers:{Authorization:`Bearer ${process.env.GROQ_API_KEY}`}})}); else add({name:"llama",displayName:"Llama (HuggingFace)",enabled:!!process.env.HF_TOKEN,model:"meta-llama/Llama-3.3-70B-Instruct",make:()=>createOpenAICompatible({name:"huggingface",baseURL:"https://router.huggingface.co/v1",headers:{Authorization:`Bearer ${process.env.HF_TOKEN}`}})});
 return registry;
}
let _registry:Map<string,RouterProvider>|null=null; export function getProviderRegistry(){if(!_registry)_registry=buildProviderRegistry();return _registry;} export function resetProviderRegistry(){_registry=null;} export function setProviderRegistryForTest(registry:Map<string,RouterProvider>){_registry=registry;}
