// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/aurora-redesign/Agent.tsx": () => import("../components/mockups/aurora-redesign/Agent.tsx"),
  "./components/mockups/aurora-redesign/Editor.tsx": () => import("../components/mockups/aurora-redesign/Editor.tsx"),
  "./components/mockups/aurora-redesign/Hub.tsx": () => import("../components/mockups/aurora-redesign/Hub.tsx")
};
