/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as UgcRouteImport } from './routes/ugc'
import { Route as TiktokRouteImport } from './routes/tiktok'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SplitRealityRouteImport } from './routes/split-reality'
import { Route as SpinRouteImport } from './routes/spin'
import { Route as SpeechRouteImport } from './routes/speech'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ReshootRouteImport } from './routes/reshoot'
import { Route as PhotoEditRouteImport } from './routes/photo-edit'
import { Route as OrchestrateRouteImport } from './routes/orchestrate'
import { Route as NexusarbRouteImport } from './routes/nexusarb'
import { Route as MusicVideoRouteImport } from './routes/music-video'
import { Route as MotionRouteImport } from './routes/motion'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LipsyncRouteImport } from './routes/lipsync'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as EditRouteImport } from './routes/edit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContentMachineRouteImport } from './routes/content-machine'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ComfyRouteImport } from './routes/comfy'
import { Route as ColorsRouteImport } from './routes/colors'
import { Route as ClipsRouteImport } from './routes/clips'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CliIndexRouteImport } from './routes/cli.index'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as CreatorDashboardRouteImport } from './routes/creator.dashboard'
import { Route as CliAuthorizeRouteImport } from './routes/cli.authorize'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiEstimateRouteImport } from './routes/api/estimate'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminSmokeRouteImport } from './routes/admin.smoke'
import { Route as AdminOrchestrationRouteImport } from './routes/admin.orchestration'
import { Route as AdminCostsRouteImport } from './routes/admin.costs'
import { Route as AdminComfyRouteImport } from './routes/admin.comfy'
import { Route as ApiPublicWatermarkVideoRouteImport } from './routes/api/public/watermark-video'
import { Route as ApiPublicWatermarkImageRouteImport } from './routes/api/public/watermark-image'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as ApiPublicLifecycleEmailsRouteImport } from './routes/api/public/lifecycle-emails'
import { Route as ApiPublicGenerateRouteImport } from './routes/api/public/generate'
import { Route as ApiPublicFreeMonthlyGrantRouteImport } from './routes/api/public/free-monthly-grant'
import { Route as ApiPublicWorkersRegisterRouteImport } from './routes/api/public/workers/register'
import { Route as ApiPublicWorkersHealthRouteImport } from './routes/api/public/workers/health'
import { Route as ApiPublicJobsTickRouteImport } from './routes/api/public/jobs/tick'
import { Route as ApiPublicCliDeviceStartRouteImport } from './routes/api/public/cli/device/start'
import { Route as ApiPublicCliDevicePollRouteImport } from './routes/api/public/cli/device/poll'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const UgcRoute = UgcRouteImport.update({
  id: '/ugc',
  path: '/ugc',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokRoute = TiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitRealityRoute = SplitRealityRouteImport.update({
  id: '/split-reality',
  path: '/split-reality',
  getParentRoute: () => rootRouteImport,
} as any)
const SpinRoute = SpinRouteImport.update({
  id: '/spin',
  path: '/spin',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechRoute = SpeechRouteImport.update({
  id: '/speech',
  path: '/speech',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ReshootRoute = ReshootRouteImport.update({
  id: '/reshoot',
  path: '/reshoot',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoEditRoute = PhotoEditRouteImport.update({
  id: '/photo-edit',
  path: '/photo-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchestrateRoute = OrchestrateRouteImport.update({
  id: '/orchestrate',
  path: '/orchestrate',
  getParentRoute: () => rootRouteImport,
} as any)
const NexusarbRoute = NexusarbRouteImport.update({
  id: '/nexusarb',
  path: '/nexusarb',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicVideoRoute = MusicVideoRouteImport.update({
  id: '/music-video',
  path: '/music-video',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionRoute = MotionRouteImport.update({
  id: '/motion',
  path: '/motion',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LipsyncRoute = LipsyncRouteImport.update({
  id: '/lipsync',
  path: '/lipsync',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentMachineRoute = ContentMachineRouteImport.update({
  id: '/content-machine',
  path: '/content-machine',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ComfyRoute = ComfyRouteImport.update({
  id: '/comfy',
  path: '/comfy',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorsRoute = ColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipsRoute = ClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CliIndexRoute = CliIndexRouteImport.update({
  id: '/cli/',
  path: '/cli/',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorDashboardRoute = CreatorDashboardRouteImport.update({
  id: '/creator/dashboard',
  path: '/creator/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CliAuthorizeRoute = CliAuthorizeRouteImport.update({
  id: '/cli/authorize',
  path: '/cli/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEstimateRoute = ApiEstimateRouteImport.update({
  id: '/api/estimate',
  path: '/api/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSmokeRoute = AdminSmokeRouteImport.update({
  id: '/smoke',
  path: '/smoke',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrchestrationRoute = AdminOrchestrationRouteImport.update({
  id: '/orchestration',
  path: '/orchestration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCostsRoute = AdminCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComfyRoute = AdminComfyRouteImport.update({
  id: '/comfy',
  path: '/comfy',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicWatermarkVideoRoute = ApiPublicWatermarkVideoRouteImport.update({
  id: '/api/public/watermark-video',
  path: '/api/public/watermark-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWatermarkImageRoute = ApiPublicWatermarkImageRouteImport.update({
  id: '/api/public/watermark-image',
  path: '/api/public/watermark-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLifecycleEmailsRoute =
  ApiPublicLifecycleEmailsRouteImport.update({
    id: '/api/public/lifecycle-emails',
    path: '/api/public/lifecycle-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGenerateRoute = ApiPublicGenerateRouteImport.update({
  id: '/api/public/generate',
  path: '/api/public/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFreeMonthlyGrantRoute =
  ApiPublicFreeMonthlyGrantRouteImport.update({
    id: '/api/public/free-monthly-grant',
    path: '/api/public/free-monthly-grant',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkersRegisterRoute =
  ApiPublicWorkersRegisterRouteImport.update({
    id: '/api/public/workers/register',
    path: '/api/public/workers/register',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkersHealthRoute = ApiPublicWorkersHealthRouteImport.update({
  id: '/api/public/workers/health',
  path: '/api/public/workers/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsTickRoute = ApiPublicJobsTickRouteImport.update({
  id: '/api/public/jobs/tick',
  path: '/api/public/jobs/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCliDeviceStartRoute = ApiPublicCliDeviceStartRouteImport.update({
  id: '/api/public/cli/device/start',
  path: '/api/public/cli/device/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCliDevicePollRoute = ApiPublicCliDevicePollRouteImport.update({
  id: '/api/public/cli/device/poll',
  path: '/api/public/cli/device/poll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/canvas': typeof CanvasRoute
  '/clips': typeof ClipsRoute
  '/colors': typeof ColorsRoute
  '/comfy': typeof ComfyRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/content-machine': typeof ContentMachineRoute
  '/dashboard': typeof DashboardRoute
  '/edit': typeof EditRoute
  '/editor': typeof EditorRoute
  '/gallery': typeof GalleryRoute
  '/gifts': typeof GiftsRoute
  '/growth': typeof GrowthRoute
  '/kids': typeof KidsRoute
  '/lipsync': typeof LipsyncRoute
  '/marketplace': typeof MarketplaceRoute
  '/motion': typeof MotionRoute
  '/music-video': typeof MusicVideoRoute
  '/nexusarb': typeof NexusarbRoute
  '/orchestrate': typeof OrchestrateRoute
  '/photo-edit': typeof PhotoEditRoute
  '/reshoot': typeof ReshootRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speech': typeof SpeechRoute
  '/spin': typeof SpinRoute
  '/split-reality': typeof SplitRealityRoute
  '/studio': typeof StudioRoute
  '/templates': typeof TemplatesRoute
  '/tiktok': typeof TiktokRoute
  '/ugc': typeof UgcRoute
  '/workflows': typeof WorkflowsRoute
  '/admin/comfy': typeof AdminComfyRoute
  '/admin/costs': typeof AdminCostsRoute
  '/admin/orchestration': typeof AdminOrchestrationRoute
  '/admin/smoke': typeof AdminSmokeRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/api/estimate': typeof ApiEstimateRoute
  '/api/mcp': typeof ApiMcpRoute
  '/cli/authorize': typeof CliAuthorizeRoute
  '/creator/dashboard': typeof CreatorDashboardRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/r/$token': typeof RTokenRoute
  '/cli/': typeof CliIndexRoute
  '/api/public/free-monthly-grant': typeof ApiPublicFreeMonthlyGrantRoute
  '/api/public/generate': typeof ApiPublicGenerateRoute
  '/api/public/lifecycle-emails': typeof ApiPublicLifecycleEmailsRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/watermark-image': typeof ApiPublicWatermarkImageRoute
  '/api/public/watermark-video': typeof ApiPublicWatermarkVideoRoute
  '/api/public/jobs/tick': typeof ApiPublicJobsTickRoute
  '/api/public/workers/health': typeof ApiPublicWorkersHealthRoute
  '/api/public/workers/register': typeof ApiPublicWorkersRegisterRoute
  '/api/public/cli/device/poll': typeof ApiPublicCliDevicePollRoute
  '/api/public/cli/device/start': typeof ApiPublicCliDeviceStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/canvas': typeof CanvasRoute
  '/clips': typeof ClipsRoute
  '/colors': typeof ColorsRoute
  '/comfy': typeof ComfyRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/content-machine': typeof ContentMachineRoute
  '/dashboard': typeof DashboardRoute
  '/edit': typeof EditRoute
  '/editor': typeof EditorRoute
  '/gallery': typeof GalleryRoute
  '/gifts': typeof GiftsRoute
  '/growth': typeof GrowthRoute
  '/kids': typeof KidsRoute
  '/lipsync': typeof LipsyncRoute
  '/marketplace': typeof MarketplaceRoute
  '/motion': typeof MotionRoute
  '/music-video': typeof MusicVideoRoute
  '/nexusarb': typeof NexusarbRoute
  '/orchestrate': typeof OrchestrateRoute
  '/photo-edit': typeof PhotoEditRoute
  '/reshoot': typeof ReshootRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speech': typeof SpeechRoute
  '/spin': typeof SpinRoute
  '/split-reality': typeof SplitRealityRoute
  '/studio': typeof StudioRoute
  '/templates': typeof TemplatesRoute
  '/tiktok': typeof TiktokRoute
  '/ugc': typeof UgcRoute
  '/workflows': typeof WorkflowsRoute
  '/admin/comfy': typeof AdminComfyRoute
  '/admin/costs': typeof AdminCostsRoute
  '/admin/orchestration': typeof AdminOrchestrationRoute
  '/admin/smoke': typeof AdminSmokeRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/api/estimate': typeof ApiEstimateRoute
  '/api/mcp': typeof ApiMcpRoute
  '/cli/authorize': typeof CliAuthorizeRoute
  '/creator/dashboard': typeof CreatorDashboardRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/r/$token': typeof RTokenRoute
  '/cli': typeof CliIndexRoute
  '/api/public/free-monthly-grant': typeof ApiPublicFreeMonthlyGrantRoute
  '/api/public/generate': typeof ApiPublicGenerateRoute
  '/api/public/lifecycle-emails': typeof ApiPublicLifecycleEmailsRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/watermark-image': typeof ApiPublicWatermarkImageRoute
  '/api/public/watermark-video': typeof ApiPublicWatermarkVideoRoute
  '/api/public/jobs/tick': typeof ApiPublicJobsTickRoute
  '/api/public/workers/health': typeof ApiPublicWorkersHealthRoute
  '/api/public/workers/register': typeof ApiPublicWorkersRegisterRoute
  '/api/public/cli/device/poll': typeof ApiPublicCliDevicePollRoute
  '/api/public/cli/device/start': typeof ApiPublicCliDeviceStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/canvas': typeof CanvasRoute
  '/clips': typeof ClipsRoute
  '/colors': typeof ColorsRoute
  '/comfy': typeof ComfyRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/content-machine': typeof ContentMachineRoute
  '/dashboard': typeof DashboardRoute
  '/edit': typeof EditRoute
  '/editor': typeof EditorRoute
  '/gallery': typeof GalleryRoute
  '/gifts': typeof GiftsRoute
  '/growth': typeof GrowthRoute
  '/kids': typeof KidsRoute
  '/lipsync': typeof LipsyncRoute
  '/marketplace': typeof MarketplaceRoute
  '/motion': typeof MotionRoute
  '/music-video': typeof MusicVideoRoute
  '/nexusarb': typeof NexusarbRoute
  '/orchestrate': typeof OrchestrateRoute
  '/photo-edit': typeof PhotoEditRoute
  '/reshoot': typeof ReshootRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speech': typeof SpeechRoute
  '/spin': typeof SpinRoute
  '/split-reality': typeof SplitRealityRoute
  '/studio': typeof StudioRoute
  '/templates': typeof TemplatesRoute
  '/tiktok': typeof TiktokRoute
  '/ugc': typeof UgcRoute
  '/workflows': typeof WorkflowsRoute
  '/admin/comfy': typeof AdminComfyRoute
  '/admin/costs': typeof AdminCostsRoute
  '/admin/orchestration': typeof AdminOrchestrationRoute
  '/admin/smoke': typeof AdminSmokeRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/api/estimate': typeof ApiEstimateRoute
  '/api/mcp': typeof ApiMcpRoute
  '/cli/authorize': typeof CliAuthorizeRoute
  '/creator/dashboard': typeof CreatorDashboardRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/r/$token': typeof RTokenRoute
  '/cli/': typeof CliIndexRoute
  '/api/public/free-monthly-grant': typeof ApiPublicFreeMonthlyGrantRoute
  '/api/public/generate': typeof ApiPublicGenerateRoute
  '/api/public/lifecycle-emails': typeof ApiPublicLifecycleEmailsRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/watermark-image': typeof ApiPublicWatermarkImageRoute
  '/api/public/watermark-video': typeof ApiPublicWatermarkVideoRoute
  '/api/public/jobs/tick': typeof ApiPublicJobsTickRoute
  '/api/public/workers/health': typeof ApiPublicWorkersHealthRoute
  '/api/public/workers/register': typeof ApiPublicWorkersRegisterRoute
  '/api/public/cli/device/poll': typeof ApiPublicCliDevicePollRoute
  '/api/public/cli/device/start': typeof ApiPublicCliDeviceStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/affiliate'
    | '/agent'
    | '/auth'
    | '/billing'
    | '/canvas'
    | '/clips'
    | '/colors'
    | '/comfy'
    | '/connect'
    | '/contact'
    | '/content-machine'
    | '/dashboard'
    | '/edit'
    | '/editor'
    | '/gallery'
    | '/gifts'
    | '/growth'
    | '/kids'
    | '/lipsync'
    | '/marketplace'
    | '/motion'
    | '/music-video'
    | '/nexusarb'
    | '/orchestrate'
    | '/photo-edit'
    | '/reshoot'
    | '/roadmap'
    | '/sitemap.xml'
    | '/speech'
    | '/spin'
    | '/split-reality'
    | '/studio'
    | '/templates'
    | '/tiktok'
    | '/ugc'
    | '/workflows'
    | '/admin/comfy'
    | '/admin/costs'
    | '/admin/orchestration'
    | '/admin/smoke'
    | '/admin/templates'
    | '/api/estimate'
    | '/api/mcp'
    | '/cli/authorize'
    | '/creator/dashboard'
    | '/legal/$slug'
    | '/r/$token'
    | '/cli/'
    | '/api/public/free-monthly-grant'
    | '/api/public/generate'
    | '/api/public/lifecycle-emails'
    | '/api/public/paystack-webhook'
    | '/api/public/watermark-image'
    | '/api/public/watermark-video'
    | '/api/public/jobs/tick'
    | '/api/public/workers/health'
    | '/api/public/workers/register'
    | '/api/public/cli/device/poll'
    | '/api/public/cli/device/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/affiliate'
    | '/agent'
    | '/auth'
    | '/billing'
    | '/canvas'
    | '/clips'
    | '/colors'
    | '/comfy'
    | '/connect'
    | '/contact'
    | '/content-machine'
    | '/dashboard'
    | '/edit'
    | '/editor'
    | '/gallery'
    | '/gifts'
    | '/growth'
    | '/kids'
    | '/lipsync'
    | '/marketplace'
    | '/motion'
    | '/music-video'
    | '/nexusarb'
    | '/orchestrate'
    | '/photo-edit'
    | '/reshoot'
    | '/roadmap'
    | '/sitemap.xml'
    | '/speech'
    | '/spin'
    | '/split-reality'
    | '/studio'
    | '/templates'
    | '/tiktok'
    | '/ugc'
    | '/workflows'
    | '/admin/comfy'
    | '/admin/costs'
    | '/admin/orchestration'
    | '/admin/smoke'
    | '/admin/templates'
    | '/api/estimate'
    | '/api/mcp'
    | '/cli/authorize'
    | '/creator/dashboard'
    | '/legal/$slug'
    | '/r/$token'
    | '/cli'
    | '/api/public/free-monthly-grant'
    | '/api/public/generate'
    | '/api/public/lifecycle-emails'
    | '/api/public/paystack-webhook'
    | '/api/public/watermark-image'
    | '/api/public/watermark-video'
    | '/api/public/jobs/tick'
    | '/api/public/workers/health'
    | '/api/public/workers/register'
    | '/api/public/cli/device/poll'
    | '/api/public/cli/device/start'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/affiliate'
    | '/agent'
    | '/auth'
    | '/billing'
    | '/canvas'
    | '/clips'
    | '/colors'
    | '/comfy'
    | '/connect'
    | '/contact'
    | '/content-machine'
    | '/dashboard'
    | '/edit'
    | '/editor'
    | '/gallery'
    | '/gifts'
    | '/growth'
    | '/kids'
    | '/lipsync'
    | '/marketplace'
    | '/motion'
    | '/music-video'
    | '/nexusarb'
    | '/orchestrate'
    | '/photo-edit'
    | '/reshoot'
    | '/roadmap'
    | '/sitemap.xml'
    | '/speech'
    | '/spin'
    | '/split-reality'
    | '/studio'
    | '/templates'
    | '/tiktok'
    | '/ugc'
    | '/workflows'
    | '/admin/comfy'
    | '/admin/costs'
    | '/admin/orchestration'
    | '/admin/smoke'
    | '/admin/templates'
    | '/api/estimate'
    | '/api/mcp'
    | '/cli/authorize'
    | '/creator/dashboard'
    | '/legal/$slug'
    | '/r/$token'
    | '/cli/'
    | '/api/public/free-monthly-grant'
    | '/api/public/generate'
    | '/api/public/lifecycle-emails'
    | '/api/public/paystack-webhook'
    | '/api/public/watermark-image'
    | '/api/public/watermark-video'
    | '/api/public/jobs/tick'
    | '/api/public/workers/health'
    | '/api/public/workers/register'
    | '/api/public/cli/device/poll'
    | '/api/public/cli/device/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AffiliateRoute: typeof AffiliateRoute
  AgentRoute: typeof AgentRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  CanvasRoute: typeof CanvasRoute
  ClipsRoute: typeof ClipsRoute
  ColorsRoute: typeof ColorsRoute
  ComfyRoute: typeof ComfyRoute
  ConnectRoute: typeof ConnectRoute
  ContactRoute: typeof ContactRoute
  ContentMachineRoute: typeof ContentMachineRoute
  DashboardRoute: typeof DashboardRoute
  EditRoute: typeof EditRoute
  EditorRoute: typeof EditorRoute
  GalleryRoute: typeof GalleryRoute
  GiftsRoute: typeof GiftsRoute
  GrowthRoute: typeof GrowthRoute
  KidsRoute: typeof KidsRoute
  LipsyncRoute: typeof LipsyncRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MotionRoute: typeof MotionRoute
  MusicVideoRoute: typeof MusicVideoRoute
  NexusarbRoute: typeof NexusarbRoute
  OrchestrateRoute: typeof OrchestrateRoute
  PhotoEditRoute: typeof PhotoEditRoute
  ReshootRoute: typeof ReshootRoute
  RoadmapRoute: typeof RoadmapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpeechRoute: typeof SpeechRoute
  SpinRoute: typeof SpinRoute
  SplitRealityRoute: typeof SplitRealityRoute
  StudioRoute: typeof StudioRoute
  TemplatesRoute: typeof TemplatesRoute
  TiktokRoute: typeof TiktokRoute
  UgcRoute: typeof UgcRoute
  WorkflowsRoute: typeof WorkflowsRoute
  ApiEstimateRoute: typeof ApiEstimateRoute
  ApiMcpRoute: typeof ApiMcpRoute
  CliAuthorizeRoute: typeof CliAuthorizeRoute
  CreatorDashboardRoute: typeof CreatorDashboardRoute
  LegalSlugRoute: typeof LegalSlugRoute
  RTokenRoute: typeof RTokenRoute
  CliIndexRoute: typeof CliIndexRoute
  ApiPublicFreeMonthlyGrantRoute: typeof ApiPublicFreeMonthlyGrantRoute
  ApiPublicGenerateRoute: typeof ApiPublicGenerateRoute
  ApiPublicLifecycleEmailsRoute: typeof ApiPublicLifecycleEmailsRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicWatermarkImageRoute: typeof ApiPublicWatermarkImageRoute
  ApiPublicWatermarkVideoRoute: typeof ApiPublicWatermarkVideoRoute
  ApiPublicJobsTickRoute: typeof ApiPublicJobsTickRoute
  ApiPublicWorkersHealthRoute: typeof ApiPublicWorkersHealthRoute
  ApiPublicWorkersRegisterRoute: typeof ApiPublicWorkersRegisterRoute
  ApiPublicCliDevicePollRoute: typeof ApiPublicCliDevicePollRoute
  ApiPublicCliDeviceStartRoute: typeof ApiPublicCliDeviceStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ugc': {
      id: '/ugc'
      path: '/ugc'
      fullPath: '/ugc'
      preLoaderRoute: typeof UgcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok': {
      id: '/tiktok'
      path: '/tiktok'
      fullPath: '/tiktok'
      preLoaderRoute: typeof TiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split-reality': {
      id: '/split-reality'
      path: '/split-reality'
      fullPath: '/split-reality'
      preLoaderRoute: typeof SplitRealityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spin': {
      id: '/spin'
      path: '/spin'
      fullPath: '/spin'
      preLoaderRoute: typeof SpinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech': {
      id: '/speech'
      path: '/speech'
      fullPath: '/speech'
      preLoaderRoute: typeof SpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reshoot': {
      id: '/reshoot'
      path: '/reshoot'
      fullPath: '/reshoot'
      preLoaderRoute: typeof ReshootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-edit': {
      id: '/photo-edit'
      path: '/photo-edit'
      fullPath: '/photo-edit'
      preLoaderRoute: typeof PhotoEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestrate': {
      id: '/orchestrate'
      path: '/orchestrate'
      fullPath: '/orchestrate'
      preLoaderRoute: typeof OrchestrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nexusarb': {
      id: '/nexusarb'
      path: '/nexusarb'
      fullPath: '/nexusarb'
      preLoaderRoute: typeof NexusarbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music-video': {
      id: '/music-video'
      path: '/music-video'
      fullPath: '/music-video'
      preLoaderRoute: typeof MusicVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion': {
      id: '/motion'
      path: '/motion'
      fullPath: '/motion'
      preLoaderRoute: typeof MotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lipsync': {
      id: '/lipsync'
      path: '/lipsync'
      fullPath: '/lipsync'
      preLoaderRoute: typeof LipsyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-machine': {
      id: '/content-machine'
      path: '/content-machine'
      fullPath: '/content-machine'
      preLoaderRoute: typeof ContentMachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comfy': {
      id: '/comfy'
      path: '/comfy'
      fullPath: '/comfy'
      preLoaderRoute: typeof ComfyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips': {
      id: '/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof ClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/': {
      id: '/cli/'
      path: '/cli'
      fullPath: '/cli/'
      preLoaderRoute: typeof CliIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/dashboard': {
      id: '/creator/dashboard'
      path: '/creator/dashboard'
      fullPath: '/creator/dashboard'
      preLoaderRoute: typeof CreatorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/authorize': {
      id: '/cli/authorize'
      path: '/cli/authorize'
      fullPath: '/cli/authorize'
      preLoaderRoute: typeof CliAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/estimate': {
      id: '/api/estimate'
      path: '/api/estimate'
      fullPath: '/api/estimate'
      preLoaderRoute: typeof ApiEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/smoke': {
      id: '/admin/smoke'
      path: '/smoke'
      fullPath: '/admin/smoke'
      preLoaderRoute: typeof AdminSmokeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orchestration': {
      id: '/admin/orchestration'
      path: '/orchestration'
      fullPath: '/admin/orchestration'
      preLoaderRoute: typeof AdminOrchestrationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/costs': {
      id: '/admin/costs'
      path: '/costs'
      fullPath: '/admin/costs'
      preLoaderRoute: typeof AdminCostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comfy': {
      id: '/admin/comfy'
      path: '/comfy'
      fullPath: '/admin/comfy'
      preLoaderRoute: typeof AdminComfyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/watermark-video': {
      id: '/api/public/watermark-video'
      path: '/api/public/watermark-video'
      fullPath: '/api/public/watermark-video'
      preLoaderRoute: typeof ApiPublicWatermarkVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/watermark-image': {
      id: '/api/public/watermark-image'
      path: '/api/public/watermark-image'
      fullPath: '/api/public/watermark-image'
      preLoaderRoute: typeof ApiPublicWatermarkImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lifecycle-emails': {
      id: '/api/public/lifecycle-emails'
      path: '/api/public/lifecycle-emails'
      fullPath: '/api/public/lifecycle-emails'
      preLoaderRoute: typeof ApiPublicLifecycleEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate': {
      id: '/api/public/generate'
      path: '/api/public/generate'
      fullPath: '/api/public/generate'
      preLoaderRoute: typeof ApiPublicGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/free-monthly-grant': {
      id: '/api/public/free-monthly-grant'
      path: '/api/public/free-monthly-grant'
      fullPath: '/api/public/free-monthly-grant'
      preLoaderRoute: typeof ApiPublicFreeMonthlyGrantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/workers/register': {
      id: '/api/public/workers/register'
      path: '/api/public/workers/register'
      fullPath: '/api/public/workers/register'
      preLoaderRoute: typeof ApiPublicWorkersRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/workers/health': {
      id: '/api/public/workers/health'
      path: '/api/public/workers/health'
      fullPath: '/api/public/workers/health'
      preLoaderRoute: typeof ApiPublicWorkersHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/tick': {
      id: '/api/public/jobs/tick'
      path: '/api/public/jobs/tick'
      fullPath: '/api/public/jobs/tick'
      preLoaderRoute: typeof ApiPublicJobsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cli/device/start': {
      id: '/api/public/cli/device/start'
      path: '/api/public/cli/device/start'
      fullPath: '/api/public/cli/device/start'
      preLoaderRoute: typeof ApiPublicCliDeviceStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cli/device/poll': {
      id: '/api/public/cli/device/poll'
      path: '/api/public/cli/device/poll'
      fullPath: '/api/public/cli/device/poll'
      preLoaderRoute: typeof ApiPublicCliDevicePollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminComfyRoute: typeof AdminComfyRoute
  AdminCostsRoute: typeof AdminCostsRoute
  AdminOrchestrationRoute: typeof AdminOrchestrationRoute
  AdminSmokeRoute: typeof AdminSmokeRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminComfyRoute: AdminComfyRoute,
  AdminCostsRoute: AdminCostsRoute,
  AdminOrchestrationRoute: AdminOrchestrationRoute,
  AdminSmokeRoute: AdminSmokeRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AffiliateRoute: AffiliateRoute,
  AgentRoute: AgentRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  CanvasRoute: CanvasRoute,
  ClipsRoute: ClipsRoute,
  ColorsRoute: ColorsRoute,
  ComfyRoute: ComfyRoute,
  ConnectRoute: ConnectRoute,
  ContactRoute: ContactRoute,
  ContentMachineRoute: ContentMachineRoute,
  DashboardRoute: DashboardRoute,
  EditRoute: EditRoute,
  EditorRoute: EditorRoute,
  GalleryRoute: GalleryRoute,
  GiftsRoute: GiftsRoute,
  GrowthRoute: GrowthRoute,
  KidsRoute: KidsRoute,
  LipsyncRoute: LipsyncRoute,
  MarketplaceRoute: MarketplaceRoute,
  MotionRoute: MotionRoute,
  MusicVideoRoute: MusicVideoRoute,
  NexusarbRoute: NexusarbRoute,
  OrchestrateRoute: OrchestrateRoute,
  PhotoEditRoute: PhotoEditRoute,
  ReshootRoute: ReshootRoute,
  RoadmapRoute: RoadmapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpeechRoute: SpeechRoute,
  SpinRoute: SpinRoute,
  SplitRealityRoute: SplitRealityRoute,
  StudioRoute: StudioRoute,
  TemplatesRoute: TemplatesRoute,
  TiktokRoute: TiktokRoute,
  UgcRoute: UgcRoute,
  WorkflowsRoute: WorkflowsRoute,
  ApiEstimateRoute: ApiEstimateRoute,
  ApiMcpRoute: ApiMcpRoute,
  CliAuthorizeRoute: CliAuthorizeRoute,
  CreatorDashboardRoute: CreatorDashboardRoute,
  LegalSlugRoute: LegalSlugRoute,
  RTokenRoute: RTokenRoute,
  CliIndexRoute: CliIndexRoute,
  ApiPublicFreeMonthlyGrantRoute: ApiPublicFreeMonthlyGrantRoute,
  ApiPublicGenerateRoute: ApiPublicGenerateRoute,
  ApiPublicLifecycleEmailsRoute: ApiPublicLifecycleEmailsRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicWatermarkImageRoute: ApiPublicWatermarkImageRoute,
  ApiPublicWatermarkVideoRoute: ApiPublicWatermarkVideoRoute,
  ApiPublicJobsTickRoute: ApiPublicJobsTickRoute,
  ApiPublicWorkersHealthRoute: ApiPublicWorkersHealthRoute,
  ApiPublicWorkersRegisterRoute: ApiPublicWorkersRegisterRoute,
  ApiPublicCliDevicePollRoute: ApiPublicCliDevicePollRoute,
  ApiPublicCliDeviceStartRoute: ApiPublicCliDeviceStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
