/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AuroraAdultRouteImport } from './routes/aurora-adult'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as ClipsRouteImport } from './routes/clips'
import { Route as ColorsRouteImport } from './routes/colors'
import { Route as ColorsShowRouteImport } from './routes/colors-show'
import { Route as ComfyRouteImport } from './routes/comfy'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContentRouteImport } from './routes/content'
import { Route as ContentMachineRouteImport } from './routes/content-machine'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DirectorRoomRouteImport } from './routes/director-room'
import { Route as DirectorsBoardRouteImport } from './routes/directors-board'
import { Route as EditRouteImport } from './routes/edit'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as EromifyRouteImport } from './routes/eromify'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as HeygenTemplatesRouteImport } from './routes/heygen-templates'
import { Route as HomeRouteImport } from './routes/home'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as LikenessRouteImport } from './routes/likeness'
import { Route as LipsyncRouteImport } from './routes/lipsync'
import { Route as LiveStudioRouteImport } from './routes/live-studio'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MasteringRouteImport } from './routes/mastering'
import { Route as MotionRouteImport } from './routes/motion'
import { Route as MusicVideoRouteImport } from './routes/music-video'
import { Route as NexusarbRouteImport } from './routes/nexusarb'
import { Route as OrchestrateRouteImport } from './routes/orchestrate'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PerformRouteImport } from './routes/perform'
import { Route as PhotoEditRouteImport } from './routes/photo-edit'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PuremixRouteImport } from './routes/puremix'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReshootRouteImport } from './routes/reshoot'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SceneBuilderRouteImport } from './routes/scene-builder'
import { Route as SceneWeaverRouteImport } from './routes/scene-weaver'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SoulRouteImport } from './routes/soul'
import { Route as SpeechRouteImport } from './routes/speech'
import { Route as SpinRouteImport } from './routes/spin'
import { Route as SplitRealityRouteImport } from './routes/split-reality'
import { Route as StoryboardRouteImport } from './routes/storyboard'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TiktokRouteImport } from './routes/tiktok'
import { Route as TiktokLiveRouteImport } from './routes/tiktok-live'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as UgcRouteImport } from './routes/ugc'
import { Route as VideoAgentStudioRouteImport } from './routes/video-agent-studio.lazy'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport })
const AccountRoute = AccountRouteImport.update({ id: '/account', path: '/account', getParentRoute: () => rootRouteImport })
const AdminRoute = AdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRouteImport })
const AdsRoute = AdsRouteImport.update({ id: '/ads', path: '/ads', getParentRoute: () => rootRouteImport })
const AffiliateRoute = AffiliateRouteImport.update({ id: '/affiliate', path: '/affiliate', getParentRoute: () => rootRouteImport })
const AgentRoute = AgentRouteImport.update({ id: '/agent', path: '/agent', getParentRoute: () => rootRouteImport })
const AuroraAdultRoute = AuroraAdultRouteImport.update({ id: '/aurora-adult', path: '/aurora-adult', getParentRoute: () => rootRouteImport })
const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport })
const AvatarRoute = AvatarRouteImport.update({ id: '/avatar', path: '/avatar', getParentRoute: () => rootRouteImport })
const BillingRoute = BillingRouteImport.update({ id: '/billing', path: '/billing', getParentRoute: () => rootRouteImport })
const CanvasRoute = CanvasRouteImport.update({ id: '/canvas', path: '/canvas', getParentRoute: () => rootRouteImport })
const ClipsRoute = ClipsRouteImport.update({ id: '/clips', path: '/clips', getParentRoute: () => rootRouteImport })
const ColorsRoute = ColorsRouteImport.update({ id: '/colors', path: '/colors', getParentRoute: () => rootRouteImport })
const ColorsShowRoute = ColorsShowRouteImport.update({ id: '/colors-show', path: '/colors-show', getParentRoute: () => rootRouteImport })
const ComfyRoute = ComfyRouteImport.update({ id: '/comfy', path: '/comfy', getParentRoute: () => rootRouteImport })
const ConnectRoute = ConnectRouteImport.update({ id: '/connect', path: '/connect', getParentRoute: () => rootRouteImport })
const ContactRoute = ContactRouteImport.update({ id: '/contact', path: '/contact', getParentRoute: () => rootRouteImport })
const ContentRoute = ContentRouteImport.update({ id: '/content', path: '/content', getParentRoute: () => rootRouteImport })
const ContentMachineRoute = ContentMachineRouteImport.update({ id: '/content-machine', path: '/content-machine', getParentRoute: () => rootRouteImport })
const DashboardRoute = DashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => rootRouteImport })
const DeleteAccountRoute = DeleteAccountRouteImport.update({ id: '/delete-account', path: '/delete-account', getParentRoute: () => rootRouteImport })
const DirectorRoomRoute = DirectorRoomRouteImport.update({ id: '/director-room', path: '/director-room', getParentRoute: () => rootRouteImport })
const DirectorsBoardRoute = DirectorsBoardRouteImport.update({ id: '/directors-board', path: '/directors-board', getParentRoute: () => rootRouteImport })
const EditRoute = EditRouteImport.update({ id: '/edit', path: '/edit', getParentRoute: () => rootRouteImport })
const EditorRoute = EditorRouteImport.update({ id: '/editor', path: '/editor', getParentRoute: () => rootRouteImport })
const EromifyRoute = EromifyRouteImport.update({ id: '/eromify', path: '/eromify', getParentRoute: () => rootRouteImport })
const GalleryRoute = GalleryRouteImport.update({ id: '/gallery', path: '/gallery', getParentRoute: () => rootRouteImport })
const GiftsRoute = GiftsRouteImport.update({ id: '/gifts', path: '/gifts', getParentRoute: () => rootRouteImport })
const GrowthRoute = GrowthRouteImport.update({ id: '/growth', path: '/growth', getParentRoute: () => rootRouteImport })
const HeygenTemplatesRoute = HeygenTemplatesRouteImport.update({ id: '/heygen-templates', path: '/heygen-templates', getParentRoute: () => rootRouteImport })
const HomeRoute = HomeRouteImport.update({ id: '/home', path: '/home', getParentRoute: () => rootRouteImport })
const JobsRoute = JobsRouteImport.update({ id: '/jobs', path: '/jobs', getParentRoute: () => rootRouteImport })
const KidsRoute = KidsRouteImport.update({ id: '/kids', path: '/kids', getParentRoute: () => rootRouteImport })
const LikenessRoute = LikenessRouteImport.update({ id: '/likeness', path: '/likeness', getParentRoute: () => rootRouteImport })
const LipsyncRoute = LipsyncRouteImport.update({ id: '/lipsync', path: '/lipsync', getParentRoute: () => rootRouteImport })
const LiveStudioRoute = LiveStudioRouteImport.update({ id: '/live-studio', path: '/live-studio', getParentRoute: () => rootRouteImport })
const MarketplaceRoute = MarketplaceRouteImport.update({ id: '/marketplace', path: '/marketplace', getParentRoute: () => rootRouteImport })
const MasteringRoute = MasteringRouteImport.update({ id: '/mastering', path: '/mastering', getParentRoute: () => rootRouteImport })
const MotionRoute = MotionRouteImport.update({ id: '/motion', path: '/motion', getParentRoute: () => rootRouteImport })
const MusicVideoRoute = MusicVideoRouteImport.update({ id: '/music-video', path: '/music-video', getParentRoute: () => rootRouteImport })
const NexusarbRoute = NexusarbRouteImport.update({ id: '/nexusarb', path: '/nexusarb', getParentRoute: () => rootRouteImport })
const OrchestrateRoute = OrchestrateRouteImport.update({ id: '/orchestrate', path: '/orchestrate', getParentRoute: () => rootRouteImport })
const PartnersRoute = PartnersRouteImport.update({ id: '/partners', path: '/partners', getParentRoute: () => rootRouteImport })
const PerformRoute = PerformRouteImport.update({ id: '/perform', path: '/perform', getParentRoute: () => rootRouteImport })
const PhotoEditRoute = PhotoEditRouteImport.update({ id: '/photo-edit', path: '/photo-edit', getParentRoute: () => rootRouteImport })
const PrivacyRoute = PrivacyRouteImport.update({ id: '/privacy', path: '/privacy', getParentRoute: () => rootRouteImport })
const PuremixRoute = PuremixRouteImport.update({ id: '/puremix', path: '/puremix', getParentRoute: () => rootRouteImport })
const ResetPasswordRoute = ResetPasswordRouteImport.update({ id: '/reset-password', path: '/reset-password', getParentRoute: () => rootRouteImport })
const ReshootRoute = ReshootRouteImport.update({ id: '/reshoot', path: '/reshoot', getParentRoute: () => rootRouteImport })
const RoadmapRoute = RoadmapRouteImport.update({ id: '/roadmap', path: '/roadmap', getParentRoute: () => rootRouteImport })
const SceneBuilderRoute = SceneBuilderRouteImport.update({ id: '/scene-builder', path: '/scene-builder', getParentRoute: () => rootRouteImport })
const SceneWeaverRoute = SceneWeaverRouteImport.update({ id: '/scene-weaver', path: '/scene-weaver', getParentRoute: () => rootRouteImport })
const SettingsRoute = SettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => rootRouteImport })
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({ id: '/sitemap.xml', path: '/sitemap.xml', getParentRoute: () => rootRouteImport })
const SoulRoute = SoulRouteImport.update({ id: '/soul', path: '/soul', getParentRoute: () => rootRouteImport })
const SpeechRoute = SpeechRouteImport.update({ id: '/speech', path: '/speech', getParentRoute: () => rootRouteImport })
const SpinRoute = SpinRouteImport.update({ id: '/spin', path: '/spin', getParentRoute: () => rootRouteImport })
const SplitRealityRoute = SplitRealityRouteImport.update({ id: '/split-reality', path: '/split-reality', getParentRoute: () => rootRouteImport })
const StoryboardRoute = StoryboardRouteImport.update({ id: '/storyboard', path: '/storyboard', getParentRoute: () => rootRouteImport })
const StudioRoute = StudioRouteImport.update({ id: '/studio', path: '/studio', getParentRoute: () => rootRouteImport })
const TemplatesRoute = TemplatesRouteImport.update({ id: '/templates', path: '/templates', getParentRoute: () => rootRouteImport })
const TermsRoute = TermsRouteImport.update({ id: '/terms', path: '/terms', getParentRoute: () => rootRouteImport })
const TiktokRoute = TiktokRouteImport.update({ id: '/tiktok', path: '/tiktok', getParentRoute: () => rootRouteImport })
const TiktokLiveRoute = TiktokLiveRouteImport.update({ id: '/tiktok-live', path: '/tiktok-live', getParentRoute: () => rootRouteImport })
const ToolsRoute = ToolsRouteImport.update({ id: '/tools', path: '/tools', getParentRoute: () => rootRouteImport })
const TutorialRoute = TutorialRouteImport.update({ id: '/tutorial', path: '/tutorial', getParentRoute: () => rootRouteImport })
const UgcRoute = UgcRouteImport.update({ id: '/ugc', path: '/ugc', getParentRoute: () => rootRouteImport })
const VideoAgentStudioRoute = VideoAgentStudioRouteImport.update({ id: '/video-agent-studio', path: '/video-agent-studio', getParentRoute: () => rootRouteImport })

const routeTree = rootRouteImport.addChildren({
  IndexRoute,
  AccountRoute,
  AdminRoute,
  AdsRoute,
  AffiliateRoute,
  AgentRoute,
  AuroraAdultRoute,
  AuthRoute,
  AvatarRoute,
  BillingRoute,
  CanvasRoute,
  ClipsRoute,
  ColorsRoute,
  ColorsShowRoute,
  ComfyRoute,
  ConnectRoute,
  ContactRoute,
  ContentRoute,
  ContentMachineRoute,
  DashboardRoute,
  DeleteAccountRoute,
  DirectorRoomRoute,
  DirectorsBoardRoute,
  EditRoute,
  EditorRoute,
  EromifyRoute,
  GalleryRoute,
  GiftsRoute,
  GrowthRoute,
  HeygenTemplatesRoute,
  HomeRoute,
  JobsRoute,
  KidsRoute,
  LikenessRoute,
  LipsyncRoute,
  LiveStudioRoute,
  MarketplaceRoute,
  MasteringRoute,
  MotionRoute,
  MusicVideoRoute,
  NexusarbRoute,
  OrchestrateRoute,
  PartnersRoute,
  PerformRoute,
  PhotoEditRoute,
  PrivacyRoute,
  PuremixRoute,
  ResetPasswordRoute,
  ReshootRoute,
  RoadmapRoute,
  SceneBuilderRoute,
  SceneWeaverRoute,
  SettingsRoute,
  SitemapDotxmlRoute,
  SoulRoute,
  SpeechRoute,
  SpinRoute,
  SplitRealityRoute,
  StoryboardRoute,
  StudioRoute,
  TemplatesRoute,
  TermsRoute,
  TiktokRoute,
  TiktokLiveRoute,
  ToolsRoute,
  TutorialRoute,
  UgcRoute,
  VideoAgentStudioRoute,
})

export const routeTree = routeTree
