/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as UgcRouteImport } from './routes/ugc'
import { Route as TiktokRouteImport } from './routes/tiktok'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SplitRealityRouteImport } from './routes/split-reality'
import { Route as SpinRouteImport } from './routes/spin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MotionRouteImport } from './routes/motion'
import { Route as LipsyncRouteImport } from './routes/lipsync'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ColorsRouteImport } from './routes/colors'
import { Route as ClipsRouteImport } from './routes/clips'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as CliAuthorizeRouteImport } from './routes/cli.authorize'
import { Route as AdminSmokeRouteImport } from './routes/admin.smoke'
import { Route as AdminOrchestrationRouteImport } from './routes/admin.orchestration'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as ApiPublicGenerateRouteImport } from './routes/api/public/generate'
import { Route as ApiPublicJobsTickRouteImport } from './routes/api/public/jobs/tick'
import { Route as ApiPublicCliDeviceStartRouteImport } from './routes/api/public/cli/device/start'
import { Route as ApiPublicCliDevicePollRouteImport } from './routes/api/public/cli/device/poll'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const UgcRoute = UgcRouteImport.update({
  id: '/ugc',
  path: '/ugc',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokRoute = TiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitRealityRoute = SplitRealityRouteImport.update({
  id: '/split-reality',
  path: '/split-reality',
  getParentRoute: () => rootRouteImport,
} as any)
const SpinRoute = SpinRouteImport.update({
  id: '/spin',
  path: '/spin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionRoute = MotionRouteImport.update({
  id: '/motion',
  path: '/motion',
  getParentRoute: () => rootRouteImport,
} as any)
const LipsyncRoute = LipsyncRouteImport.update({
  id: '/lipsync',
  path: '/lipsync',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorsRoute = ColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipsRoute = ClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CliAuthorizeRoute = CliAuthorizeRouteImport.update({
  id: '/cli/authorize',
  path: '/cli/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSmokeRoute = AdminSmokeRouteImport.update({
  id: '/smoke',
  path: '/smoke',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrchestrationRoute = AdminOrchestrationRouteImport.update({
  id: '/orchestration',
  path: '/orchestration',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGenerateRoute = ApiPublicGenerateRouteImport.update({
  id: '/api/public/generate',
  path: '/api/public/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsTickRoute = ApiPublicJobsTickRouteImport.update({
  id: '/api/public/jobs/tick',
  path: '/api/public/jobs/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCliDeviceStartRoute = ApiPublicCliDeviceStartRouteImport.update({
  id: '/api/public/cli/device/start',
  path: '/api/public/cli/device/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCliDevicePollRoute = ApiPublicCliDevicePollRouteImport.update({
  id: '/api/public/cli/device/poll',
  path: '/api/public/cli/device/poll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/canvas': typeof CanvasRoute
  '/clips': typeof ClipsRoute
  '/colors': typeof ColorsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/gifts': typeof GiftsRoute
  '/lipsync': typeof LipsyncRoute
  '/motion': typeof MotionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spin': typeof SpinRoute
  '/split-reality': typeof SplitRealityRoute
  '/studio': typeof StudioRoute
  '/tiktok': typeof TiktokRoute
  '/ugc': typeof UgcRoute
  '/workflows': typeof WorkflowsRoute
  '/admin/orchestration': typeof AdminOrchestrationRoute
  '/admin/smoke': typeof AdminSmokeRoute
  '/cli/authorize': typeof CliAuthorizeRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/r/$token': typeof RTokenRoute
  '/api/public/generate': typeof ApiPublicGenerateRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/jobs/tick': typeof ApiPublicJobsTickRoute
  '/api/public/cli/device/poll': typeof ApiPublicCliDevicePollRoute
  '/api/public/cli/device/start': typeof ApiPublicCliDeviceStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/canvas': typeof CanvasRoute
  '/clips': typeof ClipsRoute
  '/colors': typeof ColorsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/gifts': typeof GiftsRoute
  '/lipsync': typeof LipsyncRoute
  '/motion': typeof MotionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spin': typeof SpinRoute
  '/split-reality': typeof SplitRealityRoute
  '/studio': typeof StudioRoute
  '/tiktok': typeof TiktokRoute
  '/ugc': typeof UgcRoute
  '/workflows': typeof WorkflowsRoute
  '/admin/orchestration': typeof AdminOrchestrationRoute
  '/admin/smoke': typeof AdminSmokeRoute
  '/cli/authorize': typeof CliAuthorizeRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/r/$token': typeof RTokenRoute
  '/api/public/generate': typeof ApiPublicGenerateRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/jobs/tick': typeof ApiPublicJobsTickRoute
  '/api/public/cli/device/poll': typeof ApiPublicCliDevicePollRoute
  '/api/public/cli/device/start': typeof ApiPublicCliDeviceStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/canvas': typeof CanvasRoute
  '/clips': typeof ClipsRoute
  '/colors': typeof ColorsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/gifts': typeof GiftsRoute
  '/lipsync': typeof LipsyncRoute
  '/motion': typeof MotionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spin': typeof SpinRoute
  '/split-reality': typeof SplitRealityRoute
  '/studio': typeof StudioRoute
  '/tiktok': typeof TiktokRoute
  '/ugc': typeof UgcRoute
  '/workflows': typeof WorkflowsRoute
  '/admin/orchestration': typeof AdminOrchestrationRoute
  '/admin/smoke': typeof AdminSmokeRoute
  '/cli/authorize': typeof CliAuthorizeRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/r/$token': typeof RTokenRoute
  '/api/public/generate': typeof ApiPublicGenerateRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/jobs/tick': typeof ApiPublicJobsTickRoute
  '/api/public/cli/device/poll': typeof ApiPublicCliDevicePollRoute
  '/api/public/cli/device/start': typeof ApiPublicCliDeviceStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/affiliate'
    | '/auth'
    | '/canvas'
    | '/clips'
    | '/colors'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/gifts'
    | '/lipsync'
    | '/motion'
    | '/sitemap.xml'
    | '/spin'
    | '/split-reality'
    | '/studio'
    | '/tiktok'
    | '/ugc'
    | '/workflows'
    | '/admin/orchestration'
    | '/admin/smoke'
    | '/cli/authorize'
    | '/legal/$slug'
    | '/r/$token'
    | '/api/public/generate'
    | '/api/public/paystack-webhook'
    | '/api/public/jobs/tick'
    | '/api/public/cli/device/poll'
    | '/api/public/cli/device/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/affiliate'
    | '/auth'
    | '/canvas'
    | '/clips'
    | '/colors'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/gifts'
    | '/lipsync'
    | '/motion'
    | '/sitemap.xml'
    | '/spin'
    | '/split-reality'
    | '/studio'
    | '/tiktok'
    | '/ugc'
    | '/workflows'
    | '/admin/orchestration'
    | '/admin/smoke'
    | '/cli/authorize'
    | '/legal/$slug'
    | '/r/$token'
    | '/api/public/generate'
    | '/api/public/paystack-webhook'
    | '/api/public/jobs/tick'
    | '/api/public/cli/device/poll'
    | '/api/public/cli/device/start'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/affiliate'
    | '/auth'
    | '/canvas'
    | '/clips'
    | '/colors'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/gifts'
    | '/lipsync'
    | '/motion'
    | '/sitemap.xml'
    | '/spin'
    | '/split-reality'
    | '/studio'
    | '/tiktok'
    | '/ugc'
    | '/workflows'
    | '/admin/orchestration'
    | '/admin/smoke'
    | '/cli/authorize'
    | '/legal/$slug'
    | '/r/$token'
    | '/api/public/generate'
    | '/api/public/paystack-webhook'
    | '/api/public/jobs/tick'
    | '/api/public/cli/device/poll'
    | '/api/public/cli/device/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AffiliateRoute: typeof AffiliateRoute
  AuthRoute: typeof AuthRoute
  CanvasRoute: typeof CanvasRoute
  ClipsRoute: typeof ClipsRoute
  ColorsRoute: typeof ColorsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  GalleryRoute: typeof GalleryRoute
  GiftsRoute: typeof GiftsRoute
  LipsyncRoute: typeof LipsyncRoute
  MotionRoute: typeof MotionRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpinRoute: typeof SpinRoute
  SplitRealityRoute: typeof SplitRealityRoute
  StudioRoute: typeof StudioRoute
  TiktokRoute: typeof TiktokRoute
  UgcRoute: typeof UgcRoute
  WorkflowsRoute: typeof WorkflowsRoute
  CliAuthorizeRoute: typeof CliAuthorizeRoute
  LegalSlugRoute: typeof LegalSlugRoute
  RTokenRoute: typeof RTokenRoute
  ApiPublicGenerateRoute: typeof ApiPublicGenerateRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicJobsTickRoute: typeof ApiPublicJobsTickRoute
  ApiPublicCliDevicePollRoute: typeof ApiPublicCliDevicePollRoute
  ApiPublicCliDeviceStartRoute: typeof ApiPublicCliDeviceStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ugc': {
      id: '/ugc'
      path: '/ugc'
      fullPath: '/ugc'
      preLoaderRoute: typeof UgcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok': {
      id: '/tiktok'
      path: '/tiktok'
      fullPath: '/tiktok'
      preLoaderRoute: typeof TiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split-reality': {
      id: '/split-reality'
      path: '/split-reality'
      fullPath: '/split-reality'
      preLoaderRoute: typeof SplitRealityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spin': {
      id: '/spin'
      path: '/spin'
      fullPath: '/spin'
      preLoaderRoute: typeof SpinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion': {
      id: '/motion'
      path: '/motion'
      fullPath: '/motion'
      preLoaderRoute: typeof MotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lipsync': {
      id: '/lipsync'
      path: '/lipsync'
      fullPath: '/lipsync'
      preLoaderRoute: typeof LipsyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips': {
      id: '/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof ClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/authorize': {
      id: '/cli/authorize'
      path: '/cli/authorize'
      fullPath: '/cli/authorize'
      preLoaderRoute: typeof CliAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/smoke': {
      id: '/admin/smoke'
      path: '/smoke'
      fullPath: '/admin/smoke'
      preLoaderRoute: typeof AdminSmokeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orchestration': {
      id: '/admin/orchestration'
      path: '/orchestration'
      fullPath: '/admin/orchestration'
      preLoaderRoute: typeof AdminOrchestrationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate': {
      id: '/api/public/generate'
      path: '/api/public/generate'
      fullPath: '/api/public/generate'
      preLoaderRoute: typeof ApiPublicGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/tick': {
      id: '/api/public/jobs/tick'
      path: '/api/public/jobs/tick'
      fullPath: '/api/public/jobs/tick'
      preLoaderRoute: typeof ApiPublicJobsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cli/device/start': {
      id: '/api/public/cli/device/start'
      path: '/api/public/cli/device/start'
      fullPath: '/api/public/cli/device/start'
      preLoaderRoute: typeof ApiPublicCliDeviceStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cli/device/poll': {
      id: '/api/public/cli/device/poll'
      path: '/api/public/cli/device/poll'
      fullPath: '/api/public/cli/device/poll'
      preLoaderRoute: typeof ApiPublicCliDevicePollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminOrchestrationRoute: typeof AdminOrchestrationRoute
  AdminSmokeRoute: typeof AdminSmokeRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrchestrationRoute: AdminOrchestrationRoute,
  AdminSmokeRoute: AdminSmokeRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AffiliateRoute: AffiliateRoute,
  AuthRoute: AuthRoute,
  CanvasRoute: CanvasRoute,
  ClipsRoute: ClipsRoute,
  ColorsRoute: ColorsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  GalleryRoute: GalleryRoute,
  GiftsRoute: GiftsRoute,
  LipsyncRoute: LipsyncRoute,
  MotionRoute: MotionRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpinRoute: SpinRoute,
  SplitRealityRoute: SplitRealityRoute,
  StudioRoute: StudioRoute,
  TiktokRoute: TiktokRoute,
  UgcRoute: UgcRoute,
  WorkflowsRoute: WorkflowsRoute,
  CliAuthorizeRoute: CliAuthorizeRoute,
  LegalSlugRoute: LegalSlugRoute,
  RTokenRoute: RTokenRoute,
  ApiPublicGenerateRoute: ApiPublicGenerateRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicJobsTickRoute: ApiPublicJobsTickRoute,
  ApiPublicCliDevicePollRoute: ApiPublicCliDevicePollRoute,
  ApiPublicCliDeviceStartRoute: ApiPublicCliDeviceStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
